name: Terraform PR Plan

on:
  push:
    paths:
      - 'Terraform_workflow/**'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: Terraform_workflow

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.7'

      - name: Terraform Init
        run: |
          cd $TF_WORKING_DIR
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=envs/pr/${{ github.head_ref }}.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Format & Validate
        run: |
          cd $TF_WORKING_DIR
          terraform fmt -check || true
          terraform validate

      - name: Terraform Plan
        run: |
          cd $TF_WORKING_DIR
          terraform plan -input=false -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: Terraform_workflow/plan.txt

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: Terraform_workflow/artifacts/
      - name: Verify downloaded artifact
        run: cat Terraform+workflow/articfacts/artifact.txt
